# Generated by Django 4.1.7 on 2024-12-12 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20)),
                ('card_expiry', models.CharField(max_length=10)),
                ('cvv', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='BillingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_bookings', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('total_slots', models.IntegerField()),
                ('available_slots', models.IntegerField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('pin', models.CharField(default=' pin your location', max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('facility_type', models.CharField(choices=[('university', 'University'), ('church', 'Church'), ('highschool', 'High School'), ('other', 'Other')], max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='parking_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' name', max_length=100)),
                ('license_plate', models.CharField(default='KCL 545', max_length=20)),
                ('time_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_time_out', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone_number', models.CharField(default='0759194307', max_length=15)),
                ('color', models.CharField(default='eg black', max_length=50)),
                ('vehicle_type', models.CharField(choices=[('lorry', 'Lorry'), ('van', 'Van'), ('matatu', 'Matatu'), ('personal', 'Personal')], default='car', max_length=20)),
                ('car_registration_number', models.CharField(max_length=20, unique=True)),
                ('parking_lot', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parkloader.parkinglot')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLoader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('parked', models.BooleanField(default=True)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('car_registration_number', models.CharField(default='UNKNOWN', max_length=100)),
                ('parking_lot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkloader.parkinglot')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkloader.billing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkloader.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_time_out', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=50)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkloader.parkinglot')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='parkloader.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='billing',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkloader.billingplan'),
        ),
        migrations.AddField(
            model_name='billing',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
