# Generated by Django 4.1.7 on 2024-12-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkloader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='owner',
        ),
    ]
