# Generated by Django 4.1.7 on 2024-12-12 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parkloader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_registration_number', models.CharField(max_length=100, unique=True)),
                ('vehicle_type', models.CharField(choices=[('lorry', 'Lorry'), ('van', 'Van'), ('matatu', 'Matatu'), ('personal', 'Personal')], default='personal', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=50)),
                ('time_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_time_out', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default='e.g., black', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.AddField(
            model_name='vehiclebooking',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkloader.parkinglot'),
        ),
        migrations.AddField(
            model_name='vehiclebooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
