# Generated by Django 4.1.7 on 2024-12-12 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkloader', '0003_alter_parkingspace_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingloader',
            name='parking_lot',
        ),
    ]
