# Generated by Django 4.1.7 on 2024-12-13 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkloader', '0004_remove_parkingloader_parking_lot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclebooking',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='vehiclebooking',
            name='parking_lot',
        ),
    ]
