# Generated by Django 4.1.7 on 2024-12-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkloader', '0005_remove_vehiclebooking_license_plate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='parking_lot',
        ),
        migrations.DeleteModel(
            name='ParkingLot',
        ),
    ]
