# Generated by Django 4.1.7 on 2024-12-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkloader', '0006_remove_vehicle_parking_lot_delete_parkinglot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='card_number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='card_expiry',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='cvv',
        ),
    ]
